
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD JGZ LETTER MOD MUL NUMBER RCV SET SNDline : SND evalueline : SET reg evalueline : JGZ evalue evalueline : ADD reg evalueline : RCV evalueline : MUL reg evalueline : MOD reg evaluereg : LETTERevalue : regevalue : NUMBER'
    
_lr_action_items = {'SND':([0,],[2,]),'SET':([0,],[3,]),'JGZ':([0,],[4,]),'ADD':([0,],[5,]),'RCV':([0,],[6,]),'MUL':([0,],[7,]),'MOD':([0,],[8,]),'$end':([1,9,10,11,12,16,19,20,21,22,23,],[0,-1,-9,-10,-8,-5,-2,-3,-4,-6,-7,]),'NUMBER':([2,4,6,10,11,12,13,14,15,17,18,],[11,11,11,-9,-10,-8,11,11,11,11,11,]),'LETTER':([2,3,4,5,6,7,8,10,11,12,13,14,15,17,18,],[12,12,12,12,12,12,12,-9,-10,-8,12,12,12,12,12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'evalue':([2,4,6,13,14,15,17,18,],[9,14,16,19,20,21,22,23,]),'reg':([2,3,4,5,6,7,8,13,14,15,17,18,],[10,13,10,15,10,17,18,10,10,10,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> SND evalue','line',2,'p_SND','parser.py',12),
  ('line -> SET reg evalue','line',3,'p_SET','parser.py',17),
  ('line -> JGZ evalue evalue','line',3,'p_JGZ','parser.py',22),
  ('line -> ADD reg evalue','line',3,'p_ADD','parser.py',28),
  ('line -> RCV evalue','line',2,'p_RCV','parser.py',34),
  ('line -> MUL reg evalue','line',3,'p_MUL','parser.py',39),
  ('line -> MOD reg evalue','line',3,'p_MOD','parser.py',43),
  ('reg -> LETTER','reg',1,'p_reg_let','parser.py',47),
  ('evalue -> reg','evalue',1,'p_eval_reg','parser.py',51),
  ('evalue -> NUMBER','evalue',1,'p_eval_num','parser.py',55),
]
